import { ContactUs } from '@components/ContactUs'
import { Footer } from '@components/Footer'
import { Header } from '@components/Header'
import { HomeCover } from '@components/HomeCover'
import Head from 'next/head'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<HomeCover />
			<ContactUs />
			<Footer />
		</div>
	)
}
